global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']

  - job_name: 'spring-app'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: /actuator/prometheus








