name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adoptium'
          java-version: '21'

      - name: Clear Maven Cache
        run: mvn clean

      - name: Build with Maven
        run: mvn clean install


