name: CI for Kafka Project

on: [push, pull_request]  # Se ejecuta en cada push o PR

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Se ejecuta en un contenedor Linux

    services:
      kafka:
        image: wurstmeister/kafka:latest  # Imagen de Kafka
        ports:
          - 9092:9092
        env:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
          - 2181:2181

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar dependencias con Maven
        run: mvn install

      - name: Ejecutar pruebas
        run: mvn test
